#web
quarkus.application.name=observeration-service
quarkus.http.port=50700
quarkus.http.io-threads=20

#monitoring
quarkus.smallrye-health.root-path=/actuator/health
quarkus.smallrye-health.liveness-path=/actuator/health/liveness
quarkus.smallrye-health.readiness-path=/actuator/health/readiness
quarkus.micrometer.export.prometheus.path=/actuator/prometheus

#openapi
quarkus.swagger-ui.always-include=false
quarkus.smallrye-openapi.store-schema-directory=doc/generated

#tracing
quarkus.otel.exporter.otlp.traces.endpoint=http://localhost:4317
quarkus.datasource.jdbc.telemetry=false
quarkus.log.category."io.opentelemetry.exporter.internal".level=OFF
quarkus.log.category."io.quarkus.opentelemetry.runtime.exporter.otlp.sender".level=OFF

#persistence
%dev.quarkus.datasource.db-kind = h2
%dev.quarkus.datasource.jdbc.url = jdbc:h2:mem:observation;DATABASE_TO_UPPER=FALSE

%test.quarkus.datasource.db-kind = h2
%test.quarkus.datasource.jdbc.url = jdbc:h2:mem:observation

%prod.quarkus.datasource.db-kind = postgresql

quarkus.datasource.jdbc.max-size=10
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.validate-in-dev-mode=false
quarkus.hibernate-orm.physical-naming-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

#adapter
adapter.timeout=10000
adapter.failureRate=0.5
adapter.openDuration=30000
adapter.circuitBreaker.enabled=true

adapter.calleeservice.url=http://localhost:50900

org.goafabric.personservice.adapter.CalleeServiceAdapter/mp-rest/url=${adapter.calleeservice.url}
org.goafabric.personservice.adapter.CalleeServiceAdapter/mp-rest/connectTimeout=${adapter.timeout}
org.goafabric.personservice.adapter.CalleeServiceAdapter/mp-rest/readTimeout=${adapter.timeout}

#https://quarkus.io/guides/smallrye-fault-tolerance#adding-resiliency-circuit-breaker
Timeout=${adapter.timeout}
CircuitBreaker/requestVolumeThreshold=10
CircuitBreaker/failureRatio=${adapter.failureRate}
CircuitBreaker/delay=${adapter.openDuration}
CircuitBreaker/enabled=${adapter.circuitBreaker.enabled}

#logging
quarkus.log.console.format=%d{HH:mm:ss} %-5p tenantId=%X{tenantId} [%X{traceId}] [%c{2.}] (%t) %s%e%n

quarkus.log.level=INFO
quarkus.log.category."org.goafabric".level=INFO
quarkus.log.category."org.flywaydb.core".level=INFO
quarkus.log.category."org.hibernate".level=INFO

#jacoco
quarkus.jacoco.report=false

quarkus.mcp.server.server-info.description="observation service"
quarkus.mcp.server.server-info.instructions="You are a medical assistant that can query the database for vitalsigns and laboratory data You are also able to give a simple diagnosis based on the returned data The vital signs can be queried by patientame The returned vital signs can be of type bloodpressure bodyheight bodyweight The laboratory data can be queried by patientame The returned laboratory data can be of type CholestorlHDL CholestorlLDL Triglycerides Glucose HemoGlobinc Do not hallucinate if you cannot find any data or match data with the request then just state this Always use german units for measures like kg cm and so on Hemoglobin is measured in % and a valid range is 4.0%-5.6% Please talk in english"

quarkus.native.resources.includes=gdt/*.gdt,ldt/**.ldt